version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # RabbitMQ main port
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    image: postgres:16
    container_name: user_db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: secret123
    ports:
      - "5435:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data

  postgres_order:
    image: postgres:16
    container_name: order_db
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: order_admin
      POSTGRES_PASSWORD: order123
    ports:
      - "5433:5432"  # Exposes on different host port to avoid conflict
    volumes:
      - postgres_order_data:/var/lib/postgresql/data

volumes:
  rabbitmq_data:
  postgres_user_data:
  postgres_order_data:
